Algoritmo "ordem crescente"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : coloca os números em ordem cresccente
// Autor(a)    : André G. Fattore
// Data atual  : 26/08/2021
Var
n1, n2: inteiro
idade: real
nome: caractere

Inicio
escreval("Informe um valor n1:")
leia(n1)
escreval("Digite um valor:")
leia(n2)

se (n1>n2) entao
escreval(n2,",", n1)
senao
escreval(n1,",",n2)



fimse



Fimalgoritmo