Algoritmo "QUADRADO DOS NUMEROS"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : André Fattore
// Data atual  : 01/09/2021
Var
cont, resposta: real


Inicio
cont<-15
enquanto cont<=200 faca
resposta<- cont^2
escreval("O quadrado de", cont, " é igual a ", resposta)
cont<-cont+1
fimenquanto

Fimalgoritmo