Algoritmo "TIMER"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    :Andé fattore
// Data atual  : 03/09/2021
Var
cont, cont1: inteiro


Inicio
   para cont de 0 ate 59 passo 1 faca
      para cont1 de 0 ate 59 passo 1 faca
         escreval(cont, ":", cont1)
         timer 333
      fimpara
   fimpara


Fimalgoritmo