Algoritmo "Área do quadrado"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Algorítimo que cálcula a área de um quadrado
// Autor(a)    : André Garcia Fattore
// Data atual  : 24/08/2021
Var
lado, area: real


Inicio
escreval("Digite o tamanho do lado do quadrado (m2):")
leia(lado)

area<- lado^2

escreval("A área do quadrado é de", area," metros quadrados")


Fimalgoritmo