Algoritmo "14) MAIOR OU MENOR QUE 10"
// Disciplina   : Linguagem e Lógica de Programação
// Professor   : Jailson 
// Descrição   : Indica se o valor informado é maior ou menor que 10
// Autor(a)    : André
// Data atual  : 28/08/2021
Var
n: inteiro


Inicio
escreval("Digite um valor")
leia(n)
se (n>10) então
escreval(n," , É MAIOR QUE 10!")
senao
escreval(n," É MENOR QUE 10!")
fimse


Fimalgoritmo
