Algoritmo "Área de um círculo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : calcula a área de um círculo
// Autor(a)    : André Fattore
// Data atual  : 24/08/2021
Var
raio, area:real


Inicio
escreval("Digite o valor do raio (m2):")
leia(raio)

area<- (raio^2) * pi

escreval("A área do círculo é:", area," metros quadrados")


Fimalgoritmo