Algoritmo "SOMA DOS VALORES DE 1 À 100"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/09/2021
Var
// Seção de Declarações das variáveis 
cont, n: inteiro

Inicio
cont<- 1
enquanto cont<=100 faca
n<- n+cont
cont<-cont+1
escreval(n)
fimenquanto


Fimalgoritmo