Algoritmo "L03D"
// Disciplina : [Lógica de Programação e JavaScript]
// Professor : Jailson Costa dos Santos
// Descrição : Aqui você descreve o que o programa faz! (função)
// Autor(a) : ANDRÉ FATTORE
// Data atual : 01/09/2021
Var
// Seção de Declarações das variáveis
cont:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
enquanto cont<=20 faca
se cont mod 2 = 1 entao
escreval(cont)
fimse
cont<-cont+1
fimenquanto

Fimalgoritmo