Algoritmo "L04C"
// Disciplina : [Lógica de Programação e JavaScript]
// Professor : Jailson Costa dos Santos
// Descrição : Aqui você descreve o que o programa faz! (função)
// Autor(a) : André Fattore
// Data atual : 03/09/2021
var
   cont:inteiro

inicio
   cont<-1
   repita

      se cont mod 4 = 0 entao
         escreval(cont)
      fimse
      cont<-cont+1




   ate cont=200

fimalgoritmo
