Algoritmo "QUADRADO COM PARA"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/09/2021
Var
cont: inteiro
quadrado: real


Inicio
para cont de 15 ate 200 passo 1 faca
quadrado<-cont^2
escreval("O quadrado de", cont, " é:",quadrado)
fimpara


Fimalgoritmo