Algoritmo "TABUADA DE UM NUMERO QUALQUER"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/09/2021
Var
n,cont,tab: inteiro


Inicio
escreval("Digite um número:")
leia(n)
para cont de 1 ate 10 passo 1 faca

tab<- n * cont

escreval(n, " *", cont, "=", tab)
fimpara


Fimalgoritmo