Algoritmo "SOMA DOS NÚMEROS INTEIROS DE 1 A 100"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : JAILSON
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : ANDRÉ FATTORE
// Data atual  : 03/09/2021
Var
// Seção de Declarações das variáveis 
cont, acum: inteiro

Inicio
para cont de 1 até 100 passo 1 faca

acum<-acum + cont

escreval(acum)
fimpara


Fimalgoritmo