Algoritmo "L05D"
// Disciplina : [Lógica de Programação e JavaScript]
// Professor : Jailson Costa dos Santos
// Descrição : Aqui você descreve o que o programa faz! (função)
// Autor(a) : André Fattore
// Data atual : 03/09/2021
var
acum, cont:inteiro


inicio
para cont de 1 ate 500 passo 1 faca

acum<-acum + cont

cont<- cont+1


fimpara
escreval("Valor da somatória:",acum)
fimalgoritmo
