Algoritmo "NUMEROS IMPARES DE 0 A 20"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : ANDRÉ FATTORE
// Data atual  : 03/09/2021
Var
   cont:inteiro


Inicio
   para cont de 0 ate 20 passo 1 faca

      se (cont mod 2 = 1) entao

         escreval(cont)
      fimse
   fimpara

Fimalgoritmo
