Algoritmo "L05G"
// Disciplina : [Lógica de Programação e JavaScript]
// Professor : Jailson Costa dos Santos
// Descrição : Aqui você descreve o que o programa faz! (função)
// Autor(a) : André Fattore
// Data atual : 03/09/2021
var
   expo,result: inteiro
inicio

result <- 1
  para expo de 0 ate 13 faca
      se expo = 0 entao
         escreval(" 1")
       fimse
         expo <- expo + 1
         result <- result * 3
         escreval(result)

  fimpara
fimalgoritmo
