Algoritmo "L05H"
// Disciplina   : Linguagem e Lógica de Programação
// Professor   : Jailson 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/09/2021
Var
res,base,expo,cont:inteiro


Inicio
escreval("Digite uma base:")
leia(base)
escreval("Digite um expoente:")
leia(expo)
res<-1
para cont de 1 ate expo  faca

res<-res*base
cont<-cont+1
fimpara

escreval(res)


Fimalgoritmo