Algoritmo "L05I"
// Disciplina   : Linguagem e Lógica de Programação
// Professor   : Jailson 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/09/2021
Var
cont,n1,n2,n3:inteiro

inicio

n1<--1
n2<-1
cont<-0
para cont de 0 ate 15 faca

n3<- n1+n2
n1<-n2
n2<-n3

cont<-cont+1
escreval(n3)
fimpara

Fimalgoritmo