Algoritmo "L05J"
// Disciplina   : Linguagem e Lógica de Programação
// Professor   : Jailson 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/09/2021
Var
tempC:inteiro
tempF:real
inicio


para tempC de 10 ate 100 passo 10 faca

tempF<- tempC * 1.8 +32

escreval(tempC, " ºC equivalem a ", tempF, " ºF.")
fimpara

Fimalgoritmo