Algoritmo "15) POSITIVO E NEGATIVO"
// Disciplina   : Linguagem e Lógica de Programação
// Professor   : Jailson
// Descrição   : Indica se o valor informado é positivo ou negativo
// Autor(a)    : André
// Data atual  : 28/08/2021
Var
   n: inteiro


Inicio
   escreval("Digite um valor")
   leia(n)
   se (n>=0) então
      escreval(n," , É POSITIVO!")
   senao
      escreval(n," É NEGATIVO!")
   fimse


Fimalgoritmo
