Algoritmo "Numeros pares e impares"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Algoritmo fala se o numero é par ou impar
// Autor(a)    : André G. Fattore
// Data atual  : 26/08/2021
Var
n: inteiro

Inicio
escreval("Digite um valor:")
leia(n)

se ((n mod 2)=0) entao
escreval("O número", n," é par")
senao
escreval("O número", n," é ímpar")
fimse


Fimalgoritmo