Algoritmo "Antecessor"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : algoritmo que imprime na tela o antecessor de um número inteiro
// Autor(a)    : André Fattore
// Data atual  : 24/08/2021
Var
n1, ant: inteiro


Inicio
escreval("Digite um número:")
leia(n1)

ant<-n1 - 1

escreval("O antecessor de", n1, " é:", ant)


Fimalgoritmo