Algoritmo "Subtração"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Faz a soma de dois números
// Autor(a)    : André Fattore
// Data atual  : 24/08/2021
Var
sub, n1, n2: inteiro


Inicio
Escreval("Digite um minuendo:")
leia(n1)
Escreval("Digite um subtraendo:")
leia(n2)

sub<- n1-n2

Escreval("O resto é igual a:", sub)



Fimalgoritmo