Algoritmo "Área de um retângulo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : calcula a área de um retângulo
// Autor(a)    : André Fattore
// Data atual  : 24/08/2021
Var
base, altura, area: inteiro


Inicio
escreval("Digite o valor da base (m2):")
leia(base)
escreval("Digite o valor da altura (m2):")
leia(altura)

area<- base*altura

escreval("A área do retângulo é:", area," metros quadrados")


Fimalgoritmo